- name: Check if official Nginx (mainline) APT repository exists
  stat:
    path: /etc/apt/sources.list.d/nginx_org_packages_mainline_ubuntu.list
  register: repo_result

- name: Add official Nginx (mainline) APT repository GPG key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: "{{ nginx_official_key }}"
    state: present
  when: repo_result.stat.exists == False

- name: Add official Nginx (mainline) APT repository
  apt_repository:
    repo: "{{ nginx_official_repo }}"
    state: present
  when: repo_result.stat.exists == False

- name: Install Nginx version needed for OpenAM module
  apt:
    name: "{{ nginx_package_name }}={{nginx_version }}"
    update_cache: yes
    state: installed
    force: yes
